/**
 * @file user.response
 * @description defines response for user entity
 * @author FOS Project
 * @meta Response Code: 50XX, 51XX
 */

import HTTP from './code.response';
export const MSG: any = {
    SUCCESS: 'Success',
    USER_DETAILS: 'User Details get successfully',
    SIGNUP_SUCCESSFULLY: 'Signup successfully, One time passcode sent to your phone No .',
    EMAIL_ALREADY_EXISTS: 'This email is already registered',
    PHONE_NO_ALREADY_EXISTS: 'This phone no is already registered',
    OTP_INVALID: 'Please enter valid OTP.',
    OTP_EXPIRED: 'OTP expired',
    OTP_VERIFIED: 'OTP verified successfully',
    OTP_RESEND: 'OTP resend successfully.',
    PHONE_NO_NOT_REGISTERED: 'Phone no is not registered',
    FORGOT_PASSWORD_ON_PHONE: 'Please check your number for password reset link',
    USERNAME_NOT_AVAILABLE: 'Username already exists. Please try using another username.',
    OTP_SEND: 'Otp has been sent successfully',
    INVALID_TOKEN: 'This Token is invalid.',
    RESET_PASSWORD: 'Your password has been updated successfully!',
    NOT_FOUND_USER: `Can't find the account.\nTry another phone number/email or sign up to create Fivestar account.`,
    USER_NAME_EXIST: 'Username exist in db',
    USER_NAME_NOT_EXIST: 'Username does not exist',
    INCORRECT_PASSWORD: `Invalid credentials The credentials you entered is incorect. Please try again.`,
    EMAIL_NOT_REGISTERED: 'Email is not registered',
    ACCOUNT_DELETED: 'Your account is deleted by admin, please contact with admin support.',
    ACCOUNT_BLOCKED: 'Your account has been temporarily blocked.Please contact with admin support.',
    LOGIN_SUCCESSFULLY: 'User login successfully',
    MAIL_VERIFICATION_LINK: 'Mail verification link sent successfully',
    LOGGED_OUT_SUCCESSFULLY: 'You have been logged out',
    PHONE_NOT_VERIFIED: 'Phone is not verified',
    OLD_AND_NEW_PASSWORD_SAME: 'The new password must be different from your current password.',
    INCORRECT_OLD_PASSWORD: 'Incorrect old password',
    INVALID_RESET_TOKEN: 'Token has been Expired',
    PASSWORD_CHANGED_SUCCESSFULLY: 'Your password has been updated successfully!',
    TOKEN_EXPIRED: 'This link has been expired',
    VALID_RESET_TOKEN: 'Valid reset token',
    SAME_OLD_AND_NEW_PHONE_NUMBER: 'You have entered the same old and new phone number',
    OLD_MOBILE_NO_NOT_VERIFIED: 'Your old phone number is not verified',
    EMAIL_NOT_VERIFIED: 'Try verifying your email address to proceed or log in with your Phone number.',
    SAME_OLD_AND_NEW_EMAIL: 'You have entered the same old and new email address.',
    START_DATE_REQUIRED: 'Start date is required',
    END_DATE_REQUIRED: 'End date is required',
    PROFILE_UPDATED: 'Profile details is updated successfully',
    EMAIL_UPDATED: 'We have sent you a verification link to verify you e-mail Id. Please check your mail and verify.',
    EMAIL_PHONE_UPDATED:
        'Your phone number has been successfully updated and verified. Also, We have sent you a verification link to verify you e-mail Id. Please check your mail and verfiy.',
    PHONE_UPDATED: 'Your phone number has been successfully updated and verified.',
    EMAIL_EXIST: 'This email is already registered',
    PHONE_NO_EXIST: 'This Phone no is already registered',
    CLIENT_PHONE_NO_EXIST: 'This Phone no is already registered as a Client in your Country',
    OTP_VERIFIED_AND_UPDATED: 'Otp verified and user info updated successfully in your Country',
    PROFILE_NOT_COMPLETED: 'Please complete your profile.',
    UNAUTHORIZED_ACCESS: 'You are not authorized to perform this action.',
    USERNAME_AVAILABLE: 'Username available',
    USER_UPDATE: 'User updated successfully',
    SOCIAL_EXIST: 'This user is already registered with different social account.',
    SOCIAL_SIGNUP_SUCCESSFULLY: 'Signup successfully.',
    SOCIAL_ACCOUNT_FORGOT_PASSWORD_NOT_POSSIBLE: 'Forgot Password is not applicable in case of Social logins.',
    SOCIAL_ACCOUNT_PASSWORD_UPDATE_ERROR: "Passwords can't be update for social accounts.",
    RESET_PASSWORD_TOKEN_NOT_FOUND: 'No user found for this token.',
    SOCIAL_ACCOUNT_ALREADY_EXIST: 'This user is already registered with social account. Please use that to login',
    SOCIAL_LOGIN_NOT_ALLOW: 'This user is already registered. Please use manual login with password',
    NAME_USERNAME_REQUIRED: 'name and username is required',
    MAX_REELS_LIMIT: 'Cannot post more than 4 reels.',
    REEL_EXIST: 'Reel with same content already active, Please try after some time.',
    COUNTRY_CODE_REQUIRED: 'Country code required',
    USER_BLOCKED_SUCCESS: 'User blocked successfully',
    USER_UNBLOCKED_SUCCESS: 'User unblocked successfully',
    INVALID_REFERRAL_CODE: 'Invalid Referral code',
    PHONE_NO_UPDATE_NOT_ALLOW: "Phone no can't be update.",
    PASSWORD_VERIFY_SUCCESSFULLY: 'Password Verify successfully.',
    CONTENT_NOT_FOUND: 'Content not found.',
    GENERAL_ERROR: 'Something went wrong, please contact administrator.',
    PASSWORD_CHECKED_SUCCESSFULLY: 'Password checked successfully',
    SOMETHING_WENT_WRONG: 'Oops! something went wrong, please try again.',
    RATING_ALREADY_EXIST: 'Rating already exist for this user.',
    EMAIL_ALREADY_EXISTS_WITH_ANOTHER_USER: 'Email already exists with another user.',
    NOT_PERMITTED: 'You are not allowed to perform this action',
    PHONE_EMAIL_REQUIRED: 'PhoneNo or Email is required.',
    CONTENT_BLOCK_ADMIN: 'Content is blocked.',
    USER_BLOCKED: 'User is blocked',
    BLOCKED_DELETED_BY_ADMIN: 'This account is Blocked/Deleted by admin. Please contact with admin support.',
    BLOCKED_USER: 'Blocked User.', //common error for user block
    NOT_FOUND_CAPTION_USER: 'User you have included in the caption does not exist',
    DOES_NOT_EXIST_USER: 'User does not exist',
};

export default {
    USER_UPDATE: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG.USER_UPDATE, type: 'USER_UPDATE' },
    SUCCESS: { httpCode: HTTP.SUCCESS, statusCode: 200, message: 'Success', type: 'Success' },
    SIGNUP_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG.SIGNUP_SUCCESSFULLY, type: 'SIGNUP_SUCCESSFULLY' },
    USER_ADMIN_SIGNUP_SUCCESSFULLY: {
        httpCode: HTTP.SUCCESS,
        statusCode: 200,
        message: MSG.USER_ADMIN_SIGNUP_SUCCESSFULLY,
        type: 'USER_ADMIN_SIGNUP_SUCCESSFULLY',
    },
    ADMIN_SIGNUP_SUCCESSFULLY: {
        httpCode: HTTP.SUCCESS,
        statusCode: 200,
        message: MSG.ADMIN_SIGNUP_SUCCESSFULLY,
        type: 'SIGNUP_SUCCESSFULLY',
    },
    ACCOUNT_BLOCKED: { httpCode: HTTP.ACCOUNT_BLOCKED, statusCode: 403, message: MSG.ACCOUNT_BLOCKED, type: 'ACCOUNT_BLOCKED' },
    ACCOUNT_DELETED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.ACCOUNT_DELETED, type: 'ACCOUNT_DELETED' },
    INCORRECT_OLD_PASSWORD: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.INCORRECT_OLD_PASSWORD,
        type: 'INCORRECT_OLD_PASSWORD',
    },
    MAIL_VERIFICATION_LINK: {
        httpCode: HTTP.SUCCESS,
        statusCode: 200,
        message: MSG.MAIL_VERIFICATION_LINK,
        type: 'MAIL_VERIFICATION_LINK',
    },
    INVALID_RESET_TOKEN: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.INVALID_RESET_TOKEN, type: 'INVALID_RESET_TOKEN' },
    VALID_RESET_TOKEN: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG.VALID_RESET_TOKEN, type: 'VALID_RESET_TOKEN' },
    LOGIN_SUCCESSFULLY: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG.LOGIN_SUCCESSFULLY, type: 'LOGIN_SUCCESSFULLY' },
    PHONE_NOT_VERIFIED: { httpCode: HTTP.BAD_REQUEST, statusCode: 411, message: MSG.PHONE_NOT_VERIFIED, type: 'PHONE_NOT_VERIFIED' },
    LOGGED_OUT_SUCCESSFULLY: {
        httpCode: HTTP.SUCCESS,
        statusCode: 200,
        message: MSG.LOGGED_OUT_SUCCESSFULLY,
        type: 'LOGGED_OUT_SUCCESSFULLY',
    },
    INCORRECT_PASSWORD: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.INCORRECT_PASSWORD, type: 'INCORRECT_PASSWORD' },
    EMAIL_EXIST: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.EMAIL_EXIST, type: 'EMAIL_EXIST' },
    USERNAME_AVAILABLE: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG.USERNAME_AVAILABLE, type: 'USERNAME_AVAILABLE' },
    USERNAME_NOT_AVAILABLE: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.USERNAME_NOT_AVAILABLE,
        type: 'USERNAME_NOT_AVAILABLE',
    },
    NOT_FOUND: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.NOT_FOUND, type: 'NOT_FOUND' },
    PHONE_NO_EXIST: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.PHONE_NO_EXIST, type: 'PHONE_NO_EXIST' },
    PHONE_NO_EXIST2: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG.PHONE_NO_EXIST, type: 'PHONE_NO_EXIST' },
    EMAIL_EXIST2: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG.EMAIL_ALREADY_EXISTS, type: 'EMAIL_ALREADY_EXISTS' },
    EMAIL_ALREADY_EXISTS_WITH_ANOTHER_USER: {
        httpCode: HTTP.SUCCESS,
        statusCode: 200,
        message: MSG.EMAIL_ALREADY_EXISTS_WITH_ANOTHER_USER,
        type: 'EMAIL_ALREADY_EXISTS_WITH_ANOTHER_USER',
    },
    REGISTRATION_ERROR: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.REGISTRATION_ERROR, type: 'REGISTRATION_ERROR' },
    USER_NAME_EXIST: { httpCode: HTTP.SUCCESS, statusCode: 200, message: MSG.USER_NAME_EXIST, type: 'USER_NAME_EXIST' },
    USER_NAME_NOT_EXIST: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.USER_NAME_NOT_EXIST, type: 'USER_NAME_NOT_EXIST' },

    OTP_VERIFIED: {
        httpCode: HTTP.SUCCESS,
        message: MSG.OTP_VERIFIED,
        statusCode: 200,
        type: 'OTP_VERIFIED',
    },
    OTP_RESEND: {
        httpCode: HTTP.SUCCESS,
        message: MSG.OTP_RESEND,
        statusCode: 200,
        type: 'OTP_RESEND',
    },
    OTP_EXPIRED: {
        httpCode: HTTP.BAD_REQUEST,
        message: MSG.OTP_EXPIRED,
        statusCode: 400,
        type: 'OTP_EXPIRED',
    },
    OTP_INVALID: {
        httpCode: HTTP.BAD_REQUEST,
        message: MSG.OTP_INVALID,
        statusCode: 400,
        type: 'OTP_INVALID',
    },

    PHONE_NO_NOT_REGISTERED: {
        httpCode: HTTP.BAD_REQUEST,
        message: MSG.PHONE_NO_NOT_REGISTERED,
        statusCode: 400,
        type: 'PHONE_NO_NOT_REGISTERED',
    },
    INVALID_PHONE_NO: {
        httpCode: HTTP.BAD_REQUEST,
        message: 'Please enter the valid last 4 digits of a phone number.',
        statusCode: 400,
        type: 'PHONE_NO_NOT_REGISTERED',
    },
    USER_DETAILS: {
        httpCode: HTTP.SUCCESS,
        message: MSG.USER_DETAILS,
        statusCode: 200,
    },
    EMAIL_NOT_REGISTERED: {
        httpCode: HTTP.BAD_REQUEST,
        message: MSG.EMAIL_NOT_REGISTERED,
        statusCode: 400,
        type: 'EMAIL_NOT_REGISTERED',
    },
    TOKEN_EXPIRED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.TOKEN_EXPIRED, type: 'TOKEN_EXPIRED' },
    INVALID_TOKEN: {
        httpCode: HTTP.UNAUTHORIZED,
        message: MSG.INVALID_TOKEN,
        statusCode: 401,
        type: 'INVALID_TOKEN',
    },
    RESET_PASSWORD: {
        httpCode: HTTP.SUCCESS,
        message: MSG.RESET_PASSWORD,
        statusCode: 200,
        type: 'RESET_PASSWORD',
    },
    OTP_SEND: { httpCode: HTTP.SUCCESS, message: MSG.OTP_SEND, statusCode: 200, type: 'OTP_SEND' },
    SOCIAL_EXIST: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.SOCIAL_EXIST, type: 'SOCIAL_EXIST' },
    PASSWORD_CHANGED_SUCCESSFULLY: {
        httpCode: HTTP.SUCCESS,
        statusCode: 200,
        message: MSG.PASSWORD_CHANGED_SUCCESSFULLY,
        type: 'PASSWORD_CHANGED_SUCCESSFULLY',
    },
    PASSWORD_VERIFY_SUCCESSFULLY: {
        httpCode: HTTP.SUCCESS,
        statusCode: 200,
        message: MSG.PASSWORD_VERIFY_SUCCESSFULLY,
        type: 'PASSWORD_VERIFY_SUCCESSFULLY',
    },
    OLD_AND_NEW_PASSWORD_SAME: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.OLD_AND_NEW_PASSWORD_SAME,
        type: 'OLD_AND_NEW_PASSWORD_SAME',
    },
    NOT_FOUND_USER404: { httpCode: HTTP.NOT_FOUND, statusCode: 404, message: MSG.NOT_FOUND_USER, type: 'NOT_FOUND_USER' },
    NOT_FOUND_USER: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.NOT_FOUND_USER, type: 'NOT_FOUND_USER' },
    EMAIL_NOT_VERIFIED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.EMAIL_NOT_VERIFIED, type: 'EMAIL_NOT_VERIFIED' },
    SOCIAL_SIGNUP_SUCCESSFULLY: {
        httpCode: HTTP.SUCCESS,
        statusCode: 200,
        message: MSG.SOCIAL_SIGNUP_SUCCESSFULLY,
        type: 'SOCIAL_SIGNUP_SUCCESSFULLY',
    },
    SOCIAL_ACCOUNT_FORGOT_PASSWORD_NOT_POSSIBLE: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.SOCIAL_ACCOUNT_FORGOT_PASSWORD_NOT_POSSIBLE,
        type: 'SOCIAL_ACCOUNT_FORGOT_PASSWORD_NOT_POSSIBLE',
    },
    SOCIAL_ACCOUNT_PASSWORD_UPDATE_ERROR: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.SOCIAL_ACCOUNT_PASSWORD_UPDATE_ERROR,
        type: 'SOCIAL_ACCOUNT_PASSWORD_UPDATE_ERROR',
    },
    RESET_PASSWORD_TOKEN_NOT_FOUND: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.RESET_PASSWORD_TOKEN_NOT_FOUND,
        type: 'RESET_PASSWORD_TOKEN_NOT_FOUND',
    },
    SOCIAL_ACCOUNT_ALREADY_EXIST: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.SOCIAL_ACCOUNT_ALREADY_EXIST,
        type: 'SOCIAL_ACCOUNT_ALREADY_EXIST',
    },
    SOCIAL_LOGIN_NOT_ALLOW: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.SOCIAL_LOGIN_NOT_ALLOW,
        type: 'SOCIAL_LOGIN_NOT_ALLOW',
    },
    NAME_USERNAME_REQUIRED: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.NAME_USERNAME_REQUIRED,
        type: 'NAME_USERNAME_REQUIRED',
    },
    MAX_REELS_LIMIT: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.MAX_REELS_LIMIT, type: 'MAX_REELS_LIMIT' },
    REEL_EXIST: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.REEL_EXIST, type: 'REEL_EXIST' },
    COUNTRY_CODE_REQUIRED: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.COUNTRY_CODE_REQUIRED,
        type: 'COUNTRY_CODE_REQUIRED',
    },
    USER_BLOCKED_SUCCESS: { httpCode: HTTP.SUCCESS, message: MSG.USER_BLOCKED_SUCCESS, statusCode: 200, type: 'USER_BLOCKED_SUCCESS' },
    USER_UNBLOCKED_SUCCESS: {
        httpCode: HTTP.SUCCESS,
        message: MSG.USER_UNBLOCKED_SUCCESS,
        statusCode: 200,
        type: 'USER_UNBLOCKED_SUCCESS',
    },
    INVALID_REFERRAL_CODE: {
        httpCode: HTTP.BAD_REQUEST,
        message: MSG.INVALID_REFERRAL_CODE,
        statusCode: 400,
        type: 'INVALID_REFERRAL_CODE',
    },
    PHONE_NO_UPDATE_NOT_ALLOW: {
        httpCode: HTTP.BAD_REQUEST,
        message: MSG.PHONE_NO_UPDATE_NOT_ALLOW,
        statusCode: 400,
        type: 'PHONE_NO_UPDATE_NOT_ALLOW',
    },
    CONTENT_NOT_FOUND: { httpCode: HTTP.BAD_REQUEST, message: MSG.CONTENT_NOT_FOUND, statusCode: 400, type: 'CONTENT_NOT_FOUND' },
    NOT_PERMITTED: { httpCode: HTTP.BAD_REQUEST, message: MSG.NOT_PERMITTED, statusCode: 400, type: 'NOT_PERMITTED' },
    USER_NOT_SUBSCRIBE: {
        httpCode: HTTP.BAD_REQUEST,
        message: 'Subscription not assigned to You.',
        statusCode: 400,
        type: 'CONTENT_NOT_FOUND',
    },
    PASSWORD_CHECKED_SUCCESSFULLY: {
        httpCode: HTTP.SUCCESS,
        statusCode: 200,
        message: MSG.PASSWORD_CHECK_SUCCESSFULLY,
        type: 'PASSWORD_CHECK_SUCCESSFULLY',
    },
    SOMETHING_WENT_WRONG: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.SOMETHING_WENT_WRONG, type: 'SOMETHING_WENT_WRONG' },
    RATING_ALREADY_EXIST: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.RATING_ALREADY_EXIST, type: 'RATING_ALREADY_EXIST' },
    PHONE_EMAIL_REQUIRED: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.PHONE_EMAIL_REQUIRED, type: 'PHONE_EMAIL_REQUIRED' },
    PROFILE_NOT_COMPLETED: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.PROFILE_NOT_COMPLETED,
        type: 'PROFILE_NOT_COMPLETED',
    },
    CONTENT_BLOCK_ADMIN: { httpCode: HTTP.BAD_REQUEST, message: MSG.CONTENT_BLOCK_ADMIN, statusCode: 400, type: 'CONTENT_BLOCK_ADMIN' },
    USER_BLOCKED: { httpCode: HTTP.BAD_REQUEST, message: MSG.USER_BLOCKED, statusCode: 400, type: 'USER_BLOCKED' },
    BLOCKED_DELETED_BY_ADMIN: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.BLOCKED_DELETED_BY_ADMIN,
        type: 'BLOCKED_DELETED_BY_ADMIN',
    },
    BLOCKED_USER: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.BLOCKED_USER, type: 'BLOCKED_USER' },
    NOT_FOUND_CAPTION_USER: {
        httpCode: HTTP.BAD_REQUEST,
        statusCode: 400,
        message: MSG.NOT_FOUND_CAPTION_USER,
        type: 'NOT_FOUND_CAPTION_USER',
    },
    DOES_NOT_EXIST_USER: { httpCode: HTTP.BAD_REQUEST, statusCode: 400, message: MSG.DOES_NOT_EXIST_USER, type: 'DOES_NOT_EXIST_USER' },
};

export const CUSTOM_SUCCESS = (data?: any, message?: string) => {
    return {
        httpCode: 200,
        statusCode: 200,
        message: message ? message : 'Success',
        data: data ? data : {},
    };
};

export const CUSTOM_ERROR = (data?: any, message?: string) => {
    return {
        httpCode: 400,
        statusCode: 400,
        message: message ? message : 'Success',
        data: data ? data : {},
    };
};
